package org.brisskit.pmi.utils;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;

public class TestSetup {
	
	private static String CREATE_TABLE =
		"CREATE TABLE PATIENTS ( " +
		       "internal_pat_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
			   "main_pat_id VARCHAR(20), " +
			   "title VARCHAR(10), " +
			   "last_name VARCHAR(25), " +
			   "first_name VARCHAR(25), " +
			   "dob TIMESTAMP, " +
			   "ethnicity VARCHAR(10), " +
			   "gender CHAR, " +
			   "pat_addr1 VARCHAR(50), " +
			   "pat_addr2 VARCHAR(50), " +
			   "pat_addr3 VARCHAR(50), " +
			   "pat_addr4 VARCHAR(50), " +
			   "postcode VARCHAR(9)," +
			   "homephone VARCHAR(25), " +
			   "workphone VARCHAR(25), " +
			   "year_of_birth VARCHAR(4), " +
			   "gp_doh_code VARCHAR(20), " +
			   "nhs_number VARCHAR(25)" +
	    ")" ;

	private static String INSERT = 
		"INSERT INTO PATIENTS " +
		"(" +
		   "main_pat_id, " +
		   "title, " +
		   "last_name, " +
		   "first_name, " +
		   "dob, " +
		   "ethnicity, " +
		   "gender, " +
		   "pat_addr1, " +
		   "pat_addr2, " +
		   "pat_addr3, " +
		   "pat_addr4, " +
		   "postcode, " +
		   "homephone, " +
		   "workphone, " +
		   "year_of_birth, " +
		   "gp_doh_code, " +
		   "nhs_number" +
		") " +
		"VALUES " +
		"( 'S0000001', 'Mr', 'Smith', 'Arthur', '1980-08-08 20:08:08', 'Caucasian', 'M', '24 Newbridge Street'," +
		"  'New Village', 'New Town', 'New County', 'LE34 6SD', '01234-456721', '09876-54321', '1980', 'gpc 123', 'NHS 4572GTDT6' ) " ;
	
	private static boolean bInit = false ;
	private static SessionFactory sessionFactory = null ;
	
	@Autowired
	public void setSessionFactory( SessionFactory sessionFactory ) {
	    TestSetup.sessionFactory = sessionFactory;
	}
	
	@Test
	public void doNothing() {}
		
	public static void initDB() {
		if( !bInit ) {
			Session session = TestSetup.sessionFactory.getCurrentSession() ;
			session.createSQLQuery( CREATE_TABLE ).executeUpdate() ;
			session.createSQLQuery( INSERT ).executeUpdate() ;	
			bInit = true ;
		}
	}

}
