DROP DATABASE PMI_DEV;

CREATE DATABASE PMI_DEV;

USE PMI_DEV;

CREATE TABLE PATIENTS ( 
INTERNAL_PAT_ID INTEGER AUTO_INCREMENT PRIMARY KEY, 
MAIN_PAT_ID VARCHAR(20), 
TITLE VARCHAR(10), 
LAST_NAME VARCHAR(25), 
FIRST_NAME VARCHAR(25), 
DOB DATETIME NULL, 
ETHNICITY VARCHAR(10), 
GENDER CHAR(1), 
PAT_ADDR1 VARCHAR(50), 
PAT_ADDR2 VARCHAR(50),
PAT_ADDR3 VARCHAR(50),
PAT_ADDR4 VARCHAR(50),
POSTCODE VARCHAR(9),
HOMEPHONE VARCHAR(25), 
WORKPHONE VARCHAR(25),
YEAR_OF_BIRTH VARCHAR(4), 
GP_DOH_CODE VARCHAR(20),
NHS_NUMBER VARCHAR(25) ) ;
		